config/routes.rb
Rails.application.routes.draw do
  root :to => "financial_operations#index"
  resources :financial_operations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/financial_operation.rb
class FinancialOperation < ApplicationRecord
    # disable STI
    self.inheritance_column = :_type_disabled
    
    validates :type, presence: true
    validates :date, presence: true
    validates :value, presence: true
    validates :cpf, presence: true
    validates :card, presence: true
    validates :ocurrence_time, presence: true
    validates :store_owner, presence: true
    validates :store_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/financial_operations_controller.rb
class FinancialOperationsController < ApplicationController

  def index
    render :index
  end

  def create
    @response = ImportService.call params[:arquivo]

    unless @response
    flash[:notice] = 'Extensão inválida'
      render :index
    else
      flash[:notice] = 'Dados importados com sucesso'
      @financial_operations = FinancialOperation.all.order(store_name: :asc, type: :asc)
      render :show
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/financial_operations_helper.rb
module FinancialOperationsHelper
end

app/views/financial_operations/index.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Importar</h5>
    <p class="card-text">
      <% if flash[:notice].present? %>
      <div class="alert alert-warning" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>


    <%= form_tag financial_operations_path, multipart: true do %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <div class="row">
        <div class="col-sm">
          <p>
            Selecione o arquivo para importar
          </p>
        </div>
      </div>


      <div class="row">
        <div class="col-sm">


          <div class="form-group">
            <%= file_field_tag 'arquivo', :required => true  %>
            <small id="emailHelp" class="form-text text-muted">Extensão permitida .txt</small>
          </div>


          <%= submit_tag 'Importar', class: 'btn btn-info' %>
        </div>
      </div>


    <% end %>
    </p>
  </div>
</div>

app/views/financial_operations/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Resumo da importacao</h5>
    <% if flash[:notice].present? %>
      <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <table class="table table-striped">
      <thead>
        <th>Tipo</th>
        <th>Data</th>
        <th>Valor</th>
        <th>CPF</th>
        <th>Cartão</th>
        <th>Hora</th>
        <th>Dono da loja</th>
        <th>Nome loja</th>
      </thead>
      <% @financial_operations.each do |financial_operation| %>
        <tr>
          <td><%= financial_operation.type %></td>
          <td><%= financial_operation.date.strftime("%d/%m/%Y") %></td>
          <td><%= financial_operation.value %></td>
          <td><%= financial_operation.cpf %></td>
          <td><%= financial_operation.card %></td>
          <td><%= financial_operation.ocurrence_time.strftime("%H:%M") %></td>
          <td><%= financial_operation.store_owner %></td>
          <td><%= financial_operation.store_name %></td>
        </tr>
      <% end %>
    </table>

    <ul class="list-group">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Quantidade de registros contidas no lote
        <span class="badge badge-primary badge-pill"><%= @response[:total] %></span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Receita bruta total
        <span class="badge badge-primary badge-pill"><%= number_to_currency(@response[:receita], :unit => "R$ ") %></span>
      </li>
    </ul>
    <%= link_to "Nova importação", financial_operations_path, class: 'btn btn-sm btn-success btn-novo' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cnab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>